** PRAKTIKA NA EVM

О поиске ошибок

* Долг компилятора

** Warning
Синтаксически верное выражения не всегда "Верно"
if (last = 5) {  
	//...
}
Во
-Werror - делает варнинги ошибками


** Проверяем программу

*** 4096 - длина пути максимального на линуксе 

*** String overflow
strcpy(dir, argv[1]); не определена длина 
getenv() не провереяет длину 
sprintf() тоже
короче, проверяй длину

*** 
snprintf(cmd, sizeof(cmd) - 1, "%s %s", "ls", dir);
тут делается до (sizeof(cmd) - 1) эл-тов.
префикс n - круто

*** printf
printf(some_string) - плохо, вдруг там процент?

* Линтеры
Стилистические ошибки
Соответствие стандарту
Запашки кода
Потенциальные уязвимости

** Примеры программ
clang-tidy
flawfinder

** CWE-### - что это?
Common Weaknesses Enumeration

** popen
Это функция запускает строку в шелл и используется в программе.
Это не безопасно, можно подставить "sudo apt troyan"))))
* Как искать ошибки
*** Halting problem
** Тесты
Cmocka, gtest
** Динамические анализаторы
Valgrind (Хорошо проверяет утечки памяти)
Sanitizer (Хорошо проверяет cтэк)

Оба провереяют:
uninitialized variables, memory leaks, ub's, out-of-bounds access ( sanitizer это делает )

также thread analyzer

**** Что такое трэды
	+-+			+-+
	| |			|  |два потока
	+-+			+-+
	 |			 |
gl++;	 |			 |	gl--;
	 |			 |


Два трэда инкременирует и декр соответвенно
1thread	    global      2thread
1. load		0	1. load
2. inc		0	2. dec
3. store	1	3. wait to store
4. store	-1	4. store

Это - _data race_

**** Как они работают?
**** UAR - use after return

** Fuzzing
AFL, Sage
** формальная верификация
Frama-C
** Аксиомы Шура-Бура М. Р. 

* Как решать задачи -Кутуев, не Дьёрдь Пойа

Единственный совет Кутуева - Разбить задачку на маленькие подпункты.

+ Есть ли готовое решение? Будь ленивым.
