* Хэширование

* Для чего-нибудь используется кроме хэш таблица
проверка целостности и подлинности
защита паролей
ускорение поиска данных
Распознование вредоносных файлов 

** Терм.
Идентификатор
Аутентификация
Авторизация

** Криптографические хэш функции
Она необратима
Прообраз можно найти брут форсом
Стойкость к поиску второго прообраза
Стойкость к коллизии

** Редукция
Отображнение R: H -> P (множество значение хэшей -> множество строк)

Редукция используется в цепочках хэшей

aaaaaa --> 0x281DAF40 --> sgfnyd --> 0x920ECF10 --> kiebgt


** Ассоциативный массив hashmap
Чтобы реализовать хэш таблицу, он должен поддерживать следуюшие функции: 
- Insert(key, value)
- Find(key)
- Remove(key)
Необходимо также реализовать обход коллизии
(обход коллизии - разрешение ситуации, где для двух прообразов хэш функции соответсвует один образ)

** Обход коллизии 
*** Открытая адресация
Мы нашли хэш и используем его как ключ для массива
Если в массиве уже есть какой-то элемент,
то пока не найдём пустой ячейку, мы идём вниз.
Нашли пустую ячейку? -> Ложим элемент в ячейку

Недостатки: трудно реальзовать удаление

*** Закрытая адресация ( метод цепочек )
вы качестве элементы в массивах хэша мы выбираем списки 

Недостатки: в одном списке может быть все элементы ассоц. массива 

** Полиноминальный хэш
Простая реализация Хэша
Мы строим многочленами с коэффицентами, которые соответсвует значениям букв из предложенной строки
Мы берём простое число, которое, желательно, должно приблизительно того же значения, что и размер алфавита

Далее, мы находим образ этого простого числа функции многочлена 

** Алгоритм Рабина-Карпа
Ещё один алгоритм на нахожение подстроки
Мы ходим скользящим окном по строке, находим хэш каждой подстроки и ищем совпадение

** MD5
Самый хайповая хэш-таблица на рынке

* Шифрование

** Типы 
- Симметричное
используется один и тот же ключ

- Ассиметричное
отправляется "в одну сторону"
есть разные ключи для шифрования и для разшифрования
*** Никому не отправляете закрытый ключ!!!
** DES algorithm
Один из старых алгоритмов шифрования
Использует идею "РАУНДОВ"
 
** RSA
Один из самых лучших алгоритмов шифрования
Использует простые числа,
Чтобы хакнуть, нужно раскладывать на большие простые числа, а это очень сложно.
